version: "3"
networks:
  webnet:
volumes:
  mongodata:
    external:
      name: mongodata
services:
  mongo:
    image: mongo:4.1.11-bionic
    ports:
      - "27017:27017"
    networks:
      - webnet
    volumes:
      - mongodata:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - web
  web:
    image: mdcarr941/banx:latest
    ports:
      - "8080:8080"
    networks:
      - webnet
    # depends_on:
    #   - mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
       MONGO_URI: "mongodb://mongo:27017/banx"
       PORT: 8080